[package]
name = "rust_component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = "0.14.15"

[dev-dependencies]
interoptopus_backend_csharp = "0.14.17"
